# Generated by Django 4.0.2 on 2022-02-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_empolyee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
