# Generated by Django 4.0.2 on 2022-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('marks', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
