# Generated by Django 4.0.2 on 2022-02-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
