# Generated by Django 4.0.2 on 2022-02-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_alter_college_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
    ]
