# Generated by Django 4.0.2 on 2022-02-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_alter_college_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
