# Generated by Django 4.0.2 on 2022-02-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('second_app', '0005_delete_college_delete_employee_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default=True, max_length=100)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Employee_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('marks', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
