# Generated by Django 4.0.2 on 2022-02-16 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0009_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='college',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.college'),
        ),
    ]
