# Generated by Django 4.0.2 on 2022-02-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0010_principal_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.college'),
        ),
    ]
