# Generated by Django 4.0.2 on 2022-02-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0011_department_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.college'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='students',
            field=models.ManyToManyField(to='second_app.Student'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='total_marks',
            field=models.IntegerField(default=True),
        ),
    ]
