# Generated by Django 4.0.2 on 2022-02-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0012_student_department_subjects_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.department'),
        ),
    ]
