# Generated by Django 4.0.2 on 2022-02-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0013_alter_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
