# Generated by Django 4.0.2 on 2022-02-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0015_car_alter_college_address_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
    ]
