# Generated by Django 4.0.2 on 2022-02-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0016_alter_car_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_column='Dept_name', max_length=100, unique=True),
        ),
    ]
