# Generated by Django 4.0.2 on 2022-02-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0017_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='is_practical',
            field=models.BooleanField(db_column='IsPractical', null=True),
        ),
    ]
