# Generated by Django 4.0.2 on 2022-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0018_alter_subjects_is_practical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
