# Generated by Django 4.0.2 on 2022-02-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0019_alter_car_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='students',
            field=models.ManyToManyField(to='second_app.Student'),
        ),
    ]
