# Generated by Django 4.0.2 on 2022-02-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0020_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='second_app.Subjects'),
        ),
    ]
