# Generated by Django 4.0.2 on 2022-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0021_remove_student_students_remove_subjects_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='student',
            field=models.ManyToManyField(to='second_app.Student'),
        ),
    ]
