# Generated by Django 4.0.2 on 2022-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0022_remove_student_subjects_subjects_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
